### ISSUE TITLE
Reduce max size of gifs

### ISSUE THREAD

**Issue by kin-au** [fac18/week3-cikp-gifsthesia#39]
This will allow to fit more on the page, and make them easier to 'read'

**Comment by redahaq** [comment]
Can we try simply changing the 'downsized_medium' in the gif script to 'fixed_height' or 'fixed_width' as detailed in the Giphy guide 'best practices by use case' https://developers.giphy.com/docs/optional-settings/#rendition-guide

This will be more DRY than resizing via CSS.. but I'm happy to try it using the img tag if that's what everyone prefers.
