### ISSUE TITLE
Console logs + comments

### ISSUE THREAD

**Issue by tonylomax** [fac18/week3-cikp-gifsthesia#55]
Time to clear those old console logs and commented out code! It would also be nice to see a few more comments in your code explaining what each thing is doing. 

![nice](https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif)

**Comment by renatajarmova** [comment]
Agree! Make it cleaner by clearing up those console logs and commented out code (you have lots!)

https://github.com/fac18/week3-cikp-gifsthesia/blob/7498ff01bf383c01c40c40bd85ff62427537fea4/src/scripts/script-lyrics.js#L43
