### ISSUE TITLE
Size of gifs are very irregular!  😥

### ISSUE THREAD

**Issue by renatajarmova** [fac18/week3-cikp-gifsthesia#56]
Try to make them all more even! 

Or perhaps this is a feature that you were happy with?! but as a user I'd like to see pictures/gifs more even!

**Comment by rosalie-baxter** [comment]
Also some of them distort a bit on different viewports - might be good to have a regular size for all then you can also then see the order more clearly also!:) 

![gif distortion](https://user-images.githubusercontent.com/45801475/68938582-8ec53880-0796-11ea-93cf-e394c603d887.png)
