### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by tonylomax** [fac18/week3-cikp-gifsthesia#64]
It's cool that you're trying to use callbacks in your ```getRandomTrackInfo``` function. I'm not sure it's technically needed though... you could just call getRandomTrackInfo with         getRandomTrackLyrics(gifGetter) instead of callback() on line 31. 

Have you tried without the callback/what was the thought process behind this?

**Comment by kin-au** [comment]
gifGetter is now called from within the getRandomTrackLyrics function.
(Thought process: we spent 30+mins trying to get the functions to run in the correct order, otherwise it was requesting the gifs before we had any lyrics. We got it to work and never touched it again)
